version: "3.8"

services:

  api:
    build:
      dockerfile: ./docker/Dockerfile
      context: ../
    ports:
      - "8000:8000"
    networks:
      - back

  postgres:
    image: postgres:latest
    hostname: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=infinf
    volumes:
      - ../postgres-data:/var/lib/postgresql/data
    ports:
      - "32768:32768"
    command: -p 32768
    networks:
      - back

  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - back

networks:
  back: